name: CI/CD

on:
  push:

env:
  ARTIFACTS_NAME: artifacts-build${{ github.run_number }}  # .zip will be automatically appended
  FIRMWARE_NAME: Blink-build${{ github.run_number }}.ino.hex
  FIRMWARE_URL: ${{ github.server_url }}/${{ github.repository }}/releases/download/${{ github.ref_name }}/$FIRMWARE_NAME
  METADATA_NAME: metadata.json

jobs:
  job_CI:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7   # https://github.com/actions/checkout#readme

      - name: Build preparation
        run: |
          echo "Updating BuildInfo.h"
          sed -i "s,currentBuildNumber = 0,currentBuildNumber = ${{ github.run_number }}," ./Blink/BuildInfo.h
          echo "... done:"
          cat ./Blink/BuildInfo.h
          echo ""
          echo "Updating metadata.json"
          sed -i "s,CI_BUILD_NUMBER,${{ github.run_number }}," ./Blink/metadata.template.json
          sed -i "s,CI_FIRMWARE_URL,${{ env.FIRMWARE_URL }}," ./Blink/metadata.template.json
          echo "... done:"
          cat ./Blink/metadata.template.json

      - name: Build
        uses: arduino/compile-sketches@v1   # https://github.com/arduino/compile-sketches#readme
        with:
          cli-compile-flags: |
            - --export-binaries
          cli-version: latest
          fqbn: 'arduino:renesas_uno:unor4wifi'
          libraries: ''
          sketch-paths: ./Blink/Blink.ino
          verbose: true

      - name: Build artifacts collection
        run: |
          mv ./Blink/metadata.template.json ./${{ env.METADATA_NAME }}
          mv ./Blink/build/arduino.renesas_uno.unor4wifi/Blink.ino.hex ./${{ env.FIRMWARE_NAME }}

      - name: Build artifacts upload
        uses: actions/upload-artifact@v7   # https://github.com/actions/upload-artifact#readme
        with:
          name: ${{ env.ARTIFACTS_NAME }}
          retention-days: 28
          path: |
            ./${{ env.METADATA_NAME }}
            ./${{ env.FIRMWARE_NAME }}


  job_CD:
    name: Continuous Delivery
    needs: job_CI
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build artifacts download
        uses: actions/download-artifact@v8   # https://github.com/actions/download-artifact#readme
        with:
          name: ${{ env.ARTIFACTS_NAME }}
          path: ./

      - name: Release
        uses: softprops/action-gh-release@v3   # https://github.com/softprops/action-gh-release
        with:
          fail_on_unmatched_files: true
          token: ${{ github.token }}           # Token needs to provide at least the permission to write content to the repo
          files: |
            ./${{ env.METADATA_NAME }}
            ./${{ env.FIRMWARE_NAME }}
