name: CI

on:
  push:

jobs:
  job_CI:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7   # https://github.com/actions/checkout#readme

      - name: Build
        uses: arduino/compile-sketches@v1   # https://github.com/arduino/compile-sketches#readme
        with:
          cli-version: latest
          fqbn: 'arduino:renesas_uno:unor4wifi'
          libraries: ''
          sketch-paths: ./Blink/Blink.ino
          verbose: true

